### ISSUE TITLE
Specify minSdkVersion in the README

### ISSUE THREAD

**Issue by Aditya94A** [ShamylZakariya/FlyoutMenus#1]
The minSdkVersion for the library is 17. A lot of developers are still supporting lower versions, i.e they can't use this library. 

Perhaps the minSdkVersion should be specified in the README?

**Comment by ShamylZakariya** [comment]
Thanks! Good call. The minSdkVersion is noted on the README now.

I've brought the minSdkVersion down to 16, and did some stuff to workaround lack of Canvas.clipPath support on SDK < 18.
