### ISSUE TITLE
Compactablility with API

### ISSUE THREAD

**Issue by Nikhil-z** [ShamylZakariya/FlyoutMenus#2]
Please make minimum API level to  14

**Comment by rhonyabdullah** [comment]
Could you want to update this un-updated [build.gradle file](https://github.com/ShamylZakariya/FlyoutMenus/blob/master/app/build.gradle) library, like retrofit  because older version of retrofit always throw null pointer exception

**Comment by Nikhil-z** [comment]
So minimum API level ( **minSdkVersion 16** ) cannot be updated due to issues from retrofit ??

**Comment by ShamylZakariya** [comment]
I haven't pushed the min API level down to 14 yet because I haven't tested it there. I don't expect any issues with retrofit, since I don't use it (here).

**Comment by ShamylZakariya** [comment]
I don't have any devices running Jelly Bean, but I tested with an emulator, and all appears good.

The 0.5.3 release appears to work fine under API 14.
https://github.com/ShamylZakariya/FlyoutMenus/releases/tag/v0.5.3

**Comment by Nikhil-z** [comment]
ok Thanks
