### ISSUE TITLE
Custom Item

### ISSUE THREAD

**Issue by MarsXan** [ShamylZakariya/FlyoutMenus#4]
Hi
Thanks for your great work 👍 
but I have a question. how to use my custom Item with your lib?
here is my object 
`public class MyItem {
    private int Id;
    private String Shape;
    private int Image;
    private int Color;
    private String Name;
    private String Text;

    public String getText() {
        return Text;
    }

    public void setText(String text) {
        Text = text;
    }

    public int getId() {
        return Id;
    }

    public void setId(int id) {
        Id = id;
    }

    public String getShape() {
        return Shape;
    }

    public void setShape(String shape) {
        Shape = shape;
    }

    public int getImage() {
        return Image;
    }

    public void setImage(int image) {
        Image = image;
    }

    public int getColor() {
        return Color;
    }

    public void setColor(int color) {
        Color = color;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }
}`

**Comment by ShamylZakariya** [comment]
I wrote a fourth demo menu which renders arbitrary Drawable elements.

https://github.com/ShamylZakariya/FlyoutMenus/blob/master/app/src/main/java/org/zakariya/flyoutmenudemo/menus/IconFlyoutMenu.java

You should be able to figure out how to write a custom adapter given the different demo adapter types in the demo app.
